//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace APIMobille.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mobile
    {
        public int MobileID { get; set; }
        public string MobileName { get; set; }
        public string CompanyName { get; set; }
        public string Price { get; set; }
    }
}
